name: {{name.snakeCase()}}
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  connectivity_plus: ^6.1.0
  google_fonts: ^6.2.1
  shared_preferences: ^2.3.2
  flutter_mobx: ^2.2.1+1
  build_runner: ^2.4.13
  mobx_codegen: ^2.6.2
  image: ^4.3.0
  fluttertoast: ^8.2.8
  intl: ^0.19.0
  cached_network_image: ^3.4.1
  url_launcher: ^6.3.1
  country_code_picker: ^3.1.0
  #  telephony: ^0.2.0
  dropdown_search: ^6.0.1
  lottie: ^3.1.3
  http: ^1.3.0
  readmore: ^3.0.0



  #new
  toastification: ^3.0.2
  showcaseview: ^4.0.1
  package_info_plus: ^8.3.0
  carousel_slider: ^5.0.0
  timelines_plus: ^1.0.7
  ticketcher: ^0.3.0
  custom_rating_bar: ^3.0.0
  image_picker: ^1.1.2
  flutter_slidable: ^4.0.0





dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/json/
